matrix:
  include:
    - language: python
      python: 3.7
      dist: xenial
      before_script:
        - cd Pi
      install:
        - pip install paho-mqtt
        - pip install serial
        - pip install RPi.GPIO
        - pip install geopy
      script:
        - python -m unittest discover


